### ISSUE TITLE
The plugin should not use the deprecated org.gradle.util.VersionNumber

### ISSUE THREAD

**Issue by eskatos** [google/osdetector-gradle-plugin#24]
In Gradle 7.1, `org.gradle.util.VersionNumber` has been soft deprecated (@Deprecated annotation).

For Gradle 7.6 we wanted to add deprecation nagging to it. Our smoke tests show that the osdetector Gradle plugin still uses the `VersionNumber`. We will postpone adding the deprecation nagging because users currently cannot resolve it.

Could you please look into removing that usage from the plugin? You can use `GradleVersion` instead.

**Comment by ejona86** [comment]
Created https://github.com/google/osdetector-gradle-plugin/pull/25 . We can do a release so people can upgrade. We'll want to do a release of protobuf-gradle-plugin as well after bumping the osdetector version, but we were talking about doing that soon already (1-2 weeks).

**Comment by ejona86** [comment]
1.7.1 is released with the fix.

**Comment by eskatos** [comment]
Thanks!

**Comment by ejona86** [comment]
protobuf-gradle-plugin 0.9.0 is released, which updates to osdetector-gradle-plugin 1.7.1
