### ISSUE TITLE
Let the plugin not use `Provider.forUseAtConfigurationTime()`

### ISSUE THREAD

**Issue by eskatos** [google/osdetector-gradle-plugin#29]
With the 0.9.2 plugin.

The plugin uses  `Provider.forUseAtConfigurationTime()` which was softly deprecated (`@Deprecated`) since Gradle 7.4.
Since Gradle 7.4 it is a noop anyway.

We would like to start nagging users about the deprecation soon (early in 8.x to be able to remove it in Gradle 9.0).
* See https://github.com/gradle/gradle/issues/21796

**Comment by ejona86** [comment]
This was fixed in 1.7.3. Now we'll need to upgrade the version used by protobuf-gradle-plugin and get a release out.
